### ISSUE TITLE
optimist needed for use in npm scripts

### ISSUE THREAD

**Issue by mixmix** [mmckegg/micro-css#2]
I set up this script 

```
    "build:css": "mcss src/index.css -o style.css",
```

and had installed micro-css with `--save-dev`

running this script I got : 

```
> mcss src/index.css -o style.css

module.js:471
    throw err;
    ^

Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/mix/projects/protozoa/protozoa.github.io/node_modules/micro-css/bin/mcss.js:9:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)


```

This is fixed when I run: 
`npm install optimist`

**Comment by mmckegg** [comment]
Whoops. For some reason it was added as a dev dependency instead.
